services:
  Dbp\Relay\BlobConnectorFilesystemBundle\Cron\CleanupCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobConnectorFilesystemBundle\Service\FilesystemService:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\BlobConnectorFilesystemBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobConnectorFilesystemBundle\Controller\:
    tags: [ 'controller.service_arguments' ]
    resource: '../../Controller'
    autowire: true
    autoconfigure: true