services:
  Dbp\Relay\BlobConnectorLocalBundle\Service\LocalDataSystemService:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\BlobConnectorLocalBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true